spring:
  profiles.active: "dev"
---
# definition of development profile - dev
spring:
  config:
    activate:
      on-profile: "dev"
  # datasource definition:
  # - embedded H2 database in file mode
  # - h2-console enabled
  # - initialized on application startup
  datasource:
    url: "jdbc:h2:~/vortex-scheduler"
    username: "sa"
    password: "password"
    driverClassName: "org.h2.Driver"
    #platform: "h2"
    initialization-mode: "embedded"
    continue-on-error: true # ensures that application startup does not fail on SQL error caused by already existing tables
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "none"
  h2:
    console.enabled: true
  quartz:
    job-store-type: jdbc # jdbc job store
    jdbc:
      initialize-schema: "always"

# logging configuration
logging:
  file.name: "vortex-scheduler.log"

# server configuration
server:
  servlet:
    context-path: "/vortex-scheduler"

# actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
# Insert configuration for other profiles here
